'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Runtime.Serialization.DataContract>
Partial Public Class Company
    <Runtime.Serialization.DataMember>
    Public Property ID As Integer
    Public Property Name As String
    Public Property Address As String
    Public Property City As String
    Public Property Phone As String
    Public Property Zip As String
    Public Property Misc As String

    '<Runtime.Serialization.IgnoreDataMember>
    Public Overridable Property Contacts As ICollection(Of Contact) = New HashSet(Of Contact)

    '<Newtonsoft.Json.JsonIgnore>
    '<Runtime.Serialization.IgnoreDataMember>
    Public Overridable Property Quotes As ICollection(Of Quote) = New HashSet(Of Quote)

End Class
