'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DatabaseContainer
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DatabaseContainer")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Companies() As DbSet(Of Company)
    Public Overridable Property Contacts() As DbSet(Of Contact)
    Public Overridable Property Quotes() As DbSet(Of Quote)
    Public Overridable Property Notes() As DbSet(Of Note)
    Public Overridable Property QuoteLines() As DbSet(Of QuoteLine)
    Public Overridable Property QuoteSections() As DbSet(Of QuoteSection)
    Public Overridable Property QuoteSectionDetails() As DbSet(Of QuoteSectionDetail)
    Public Overridable Property Settings() As DbSet(Of Setting)

End Class
